# Generated by Django 4.2.20 on 2025-03-25 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productivity_habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voicenote',
            name='related_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_notes', to='productivity_habits.quarterlyquest'),
        ),
        migrations.AddField(
            model_name='voicenote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlyquest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='morningmanifesto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morning_manifestos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitee',
            name='social_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='productivity_habits.socialevent'),
        ),
        migrations.AddField(
            model_name='invitee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='focussession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='productivity_habits.quarterlyquest'),
        ),
        migrations.AddField(
            model_name='focussession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreset',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='morningmanifesto',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='invitee',
            unique_together={('social_event', 'email')},
        ),
    ]
